export const environment = {
  production: false,
  entreprenlyProviderApiBaseUrl: 'http://localhost:3000/api/v1',
  entreprenlyProviderSalesEndpointPath: '/sales',
  entreprenlyProviderProfileEndpointPath: '/profile',
  entreprenlyProviderSalesProductsEndpointPath: '/sales-products',
  entreprenlyProviderInventoryProductsEndpointPath: '/inventory-products',
  entreprenlyProviderCashRegistersEndpointPath: '/cash-registers',
  entreprenlyProviderSubscriptionEndpointPath: '/subscription',
  entreprenlyProviderSubscriptionDashboardEndpointPath: '/subscription-dashboard/1',
  entreprenlyProviderInventoryLotsEndpointPath: '/inventory-lots',
  entreprenlyProviderInventoryUnitProductsEndpointPath: '/inventory-unit-products',
  entreprenlyProviderInventoryUnitLotsEndpointPath: '/inventory-unit-lots',
  entreprenlyProviderInventoryWeightProductsEndpointPath: '/inventory-weight-products',
  entreprenlyProviderInventoryWeightLotsEndpointPath: '/inventory-weight-lots',
  entreprenlyProviderInventoryStockAlertsEndpointPath: '/inventory-stock-alerts',
  entreprenlyProviderSubscriptionActivationEndpointPath: '/subscription-payment-confirmation/1',
};
